### ISSUE TITLE
k8s oars init job "Import dashboard failed for an unknown reason"

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-oars#28]
## Description

After several tests performed, it was found that the init job in k8s for oars was failing to import all the data correctly.

The error is below:

```bash
Collecting superset-api-client<0.7,>=0.6
--
Thu, Apr 27 2023 1:54:29 pm | Downloading superset_api_client-0.6.0-py3-none-any.whl (16 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting requests-oauthlib
Thu, Apr 27 2023 1:54:29 pm | Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting requests>=2.0.0
Thu, Apr 27 2023 1:54:29 pm | Downloading requests-2.29.0-py3-none-any.whl (62 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting pyyaml>=6.0
Thu, Apr 27 2023 1:54:29 pm | Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting charset-normalizer<4,>=2
Thu, Apr 27 2023 1:54:29 pm | Downloading charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting idna<4,>=2.5
Thu, Apr 27 2023 1:54:29 pm | Downloading idna-3.4-py3-none-any.whl (61 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting urllib3<1.27,>=1.21.1
Thu, Apr 27 2023 1:54:29 pm | Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting certifi>=2017.4.17
Thu, Apr 27 2023 1:54:29 pm | Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
Thu, Apr 27 2023 1:54:29 pm | Collecting oauthlib>=3.0.0
Thu, Apr 27 2023 1:54:29 pm | Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
Thu, Apr 27 2023 1:54:29 pm | Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, oauthlib, requests-oauthlib, pyyaml, superset-api-client
Thu, Apr 27 2023 1:54:30 pm | Successfully installed certifi-2022.12.7 charset-normalizer-3.1.0 idna-3.4 oauthlib-3.2.2 pyyaml-6.0 requests-2.29.0 requests-oauthlib-1.3.1 superset-api-client-0.6.0 urllib3-1.26.15
Thu, Apr 27 2023 1:54:30 pm | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Thu, Apr 27 2023 1:54:30 pm | WARNING: You are using pip version 21.1.3; however, version 23.1.2 is available.
Thu, Apr 27 2023 1:54:30 pm | You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Thu, Apr 27 2023 1:54:32 pm | Traceback (most recent call last):
Thu, Apr 27 2023 1:54:32 pm | File "/app/oars/pythonpath/superset-dashboard.py", line 108, in <module>
Thu, Apr 27 2023 1:54:32 pm | update_assets()
Thu, Apr 27 2023 1:54:32 pm | File "/app/oars/pythonpath/superset-dashboard.py", line 54, in update_assets
Thu, Apr 27 2023 1:54:32 pm | getattr(superset, asset_type).import_file(
Thu, Apr 27 2023 1:54:32 pm | File "/usr/local/lib/python3.8/site-packages/supersetapiclient/base.py", line 291, in import_file
Thu, Apr 27 2023 1:54:32 pm | raise_for_status(response)
Thu, Apr 27 2023 1:54:32 pm | File "/usr/local/lib/python3.8/site-packages/supersetapiclient/base.py", line 44, in raise_for_status
Thu, Apr 27 2023 1:54:32 pm | raise ComplexBadRequestError(*e.args, request=e.request, response=e.response, errors=errors) from None
Thu, Apr 27 2023 1:54:32 pm | supersetapiclient.exceptions.ComplexBadRequestError: [
Thu, Apr 27 2023 1:54:32 pm | {
Thu, Apr 27 2023 1:54:32 pm | "message": "Import dashboard failed for an unknown reason",
Thu, Apr 27 2023 1:54:32 pm | "error_type": "GENERIC_COMMAND_ERROR",
Thu, Apr 27 2023 1:54:32 pm | "level": "error",
Thu, Apr 27 2023 1:54:32 pm | "extra": {
Thu, Apr 27 2023 1:54:32 pm | "issue_codes": [
Thu, Apr 27 2023 1:54:32 pm | {
Thu, Apr 27 2023 1:54:32 pm | "code": 1010,
Thu, Apr 27 2023 1:54:32 pm | "message": "Issue 1010 - Superset encountered an error while running a command."
Thu, Apr 27 2023 1:54:32 pm | }
Thu, Apr 27 2023 1:54:32 pm | ]
Thu, Apr 27 2023 1:54:32 pm | }
Thu, Apr 27 2023 1:54:32 pm | }
Thu, Apr 27 2023 1:54:32 pm | ]
```

While superset logs:
[superset logs.txt](https://github.com/openedx/tutor-contrib-oars/files/11347135/superset.logs.txt)

Based on the superset logs, it seems it's related to this bug https://github.com/apache/superset/issues/22506 but it's unclear why it worked on tutor local and not for tutor k8s.

It's also curious that you can run the local python script generated by tutor stored in `env/plugins/oars/apps/pythonpath/superset-dashboard.py` manually, and the dashboard it's imported correctly in you set the following variable into the script:

SUPERSET_DATA_ASSETS_DIR = "env/plugins/oars/apps/data/superset"

Also, you can comment the line that removes the temporary zip file, check for that file in your system (probably in `/tmp`) and import it manually through the superset interface in dashboard. (there should be 4 temporary zip files, search the one that has a folder called `dashboard`)

**Comment by mariajgrimaldi** [comment]
For the time being, how can we emulate what the oars job does? Is there a way to do that?

**Comment by Ian2012** [comment]
Importing the file manually (by following the instructions at the bottom) or calling the generated script generated by tutor stored in `env/plugins/oars/apps/pythonpath/superset-dashboard.py`

**Comment by bmtcril** [comment]
Note that the majority of charts won't work with anything but the demo course anyways until the new event sink project lands next week. When that happens new data sources, charts, reports etc will need to be done.

**Comment by bmtcril** [comment]
@Ian2012 is there any chance that superset server was running 2.1? I've seen similar issues when I accidentally pulled a 2.1 image.

**Comment by Ian2012** [comment]
@bmtcril nop:

![image](https://github.com/openedx/tutor-contrib-oars/assets/33465240/7426a161-5377-4a25-90ad-9dcd39f4172b)

2.1 image also breaks our authentication, not sure why
